- name: Configure /etc/hosts for hostname resolution
  hosts: all
  become: true

  tasks:
    - name: Backup existing /etc/hosts
      copy:
        src: /etc/hosts
        dest: /etc/hosts.bak
        remote_src: yes

    - name: Gather host information
      ansible.builtin.set_fact:
        host_entries: "{{ host_entries | default([]) + [{'ip': hostvars[item].ansible_default_ipv4.address | default(item), 'hostname': hostvars[item].inventory_hostname | default(item)}] }}"
      loop: "{{ ansible_play_hosts }}"
      run_once: true  # Gather host info once on the first host.

    - name: Debug gathered host information
      ansible.builtin.debug:
        msg: "{{ host_entries }}"
      when: host_entries is not none
      
    - name: Update /etc/hosts
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |
          # Ansible managed hosts entries
          {% for host in host_entries %}
          {{ host.ip }} {{ host.hostname }}
          {% endfor %}
        state: present
        marker: "# {mark} ANSIBLE MANAGED HOSTS"
