- name: Configure /etc/hosts for hostname resolution
  hosts: all
  become: true

  tasks:
    - name: Backup existing /etc/hosts
      copy:
        src: /etc/hosts
        dest: /etc/hosts.bak
        remote_src: yes

    - name: Gather host information
      ansible.builtin.set_fact:
        host_entries: "{{ host_entries | default([]) + [{'ip': hostvars[item].ansible_host | default(item), 'hostname': item}] }}"
      loop: "{{ ansible_play_hosts }}"
      delegate_to: localhost
      run_once: true # Gather host info once on the first host.

    - name: Update /etc/hosts
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |
          # Ansible managed hosts entries
          {% for host in host_entries %}
          {{ host.ip }} {{ host.hostname }}
          {% endfor %}
        state: present
        marker: "# {mark} ANSIBLE MANAGED HOSTS"
