---
- name: Deploy LAMP stack on each server and single PHP page
  hosts: webservers # specify servers
  become: yes # use sudo privileges
  tasks:
    - name: Update package manager
      apt:
        update_cache: yes

    - name: Install LAMP stack # Use `package` to install multiple packages
      apt:
        name:
          - apache2
          - php
          - libapache2-mod-php
          - mariadb-server
        state: latest

    - name: Create PHP info page
      copy:
        content: |
          <?php
          echo "Hello from " . gethostname() . "!";
          ?>
        dest: /var/www/html/index.php

    - name: Start apache, php, and mariadb
      service:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      with_items:
        - apache2
        - mariadb
